name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: iterative/setup-cml@v2
        with:
          vega: false
      - uses: iterative/setup-dvc@v1

      - name: Install Packages
        run: |
          make install

      - name: Train with DVC import (HF source)
        run: make train_dvc

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval_cml_and_dvc
