name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  train-and-report:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
      HF_DATASET_URL: ${{ vars.HF_DATASET_URL }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: iterative/setup-cml@v2
        with:
          vega: false
      - uses: iterative/setup-dvc@v1

      - name: Install Packages
        run: make install

      - name: Train with DVC import
        run: make train_dvc

      - name: Check DVC status
        run: dvc status -c

      - name: Create CML report and comment PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HF_TOKEN: ${{ env.HF_TOKEN }}
        run: make eval_cml_and_dvc
